version: "3.8"

services:

  webserver:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - users_api
    networks:
      - dev_network

  users_api:
    build:
      context: ./APIS
    deploy:
      replicas: 1  # Reducido para evitar conflictos
      resources:
        limits:
          cpus: "0.2"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    ports:
      - "4000:4010"  # Cambia a un solo puerto, o usa puertos únicos por instancia
    volumes:
      - ./APIS/usuarios:/usr/userAPI
    networks:
      - dev_network

  db_dev:
    image: postgres:17 # Usar una versión estable de PostgreSQL en lugar de un Dockerfile personalizado
    container_name: users_db_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./users_data_dev:/var/lib/postgresql/data
      - ./pg_logs:/var/log/postgresql
    networks:
      - dev_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev_pgadmin
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: cafe@admin.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge

volumes:
  cafe_db_data:
